<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11pt; color: #222; }
    .page { padding: 40px 50px; }
    .header { display: flex; justify-content: space-between; border-bottom: 3px solid #3b82f6; padding-bottom: 15px; margin-bottom: 20px; }
    .company-name { font-size: 22pt; font-weight: bold; color: #3b82f6; }
    .company-sub { font-size: 8pt; color: #666; }
    .ref { font-size: 9pt; color: #666; text-align: right; }
    h1 { text-align: center; font-size: 16pt; text-transform: uppercase; letter-spacing: 3px; color: #1e293b; margin: 20px 0; border-top: 1px solid #ddd; border-bottom: 1px solid #ddd; padding: 8px 0; }
    .info-box { background: #f8f9fc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 15px; margin: 15px 0; }
    .info-row { display: flex; margin-bottom: 8px; }
    .info-label { width: 170px; color: #64748b; font-size: 9pt; font-weight: bold; }
    .info-value { flex: 1; font-weight: bold; }
    .old-sal { color: #999; text-decoration: line-through; }
    .new-sal { color: #16a34a; font-size: 13pt; }
    .badge { background: #16a34a; color: white; padding: 2px 10px; border-radius: 4px; font-size: 10pt; }
    .signature-row { display: flex; justify-content: space-between; margin-top: 60px; }
    .sig-box { width: 200px; border-top: 1px solid #333; padding-top: 6px; font-size: 9pt; }
    p { font-size: 10pt; line-height: 1.7; color: #444; }
    .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 8pt; color: #999; text-align: center; }
</style>
</head>
<body>
<div class="page">
    <div class="header">
        <div>
            <div class="company-name">HRMS</div>
            <div class="company-sub">Human Resource Management System</div>
            <div class="company-sub">123 Business Park, Tech City, India – 400001</div>
        </div>
        <div class="ref">
            <div>Date: {{ $incrementLetter->effective_date->format('d F Y') }}</div>
            <div>Ref: IL-{{ str_pad($incrementLetter->id, 4, '0', STR_PAD_LEFT) }}</div>
        </div>
    </div>
    <h1>Salary Increment Letter</h1>
    <p>Dear <strong>{{ $incrementLetter->employee->full_name }}</strong>,</p>
    <p>We are pleased to inform you that the management has decided to revise your salary, effective <strong>{{ $incrementLetter->effective_date->format('d F Y') }}</strong>. This reflects your outstanding contribution to the organization.</p>
    <div class="info-box">
        <div class="info-row"><div class="info-label">Employee Code:</div><div class="info-value">{{ $incrementLetter->employee->employee_code }}</div></div>
        <div class="info-row"><div class="info-label">Name:</div><div class="info-value">{{ $incrementLetter->employee->full_name }}</div></div>
        <div class="info-row"><div class="info-label">Designation:</div><div class="info-value">{{ $incrementLetter->employee->designation?->name ?? 'N/A' }}</div></div>
        <div class="info-row"><div class="info-label">Department:</div><div class="info-value">{{ $incrementLetter->employee->department?->name ?? 'N/A' }}</div></div>
        <div class="info-row">
            <div class="info-label">Previous CTC:</div>
            <div class="info-value"><span class="old-sal">₹ {{ number_format($incrementLetter->old_salary, 2) }}</span></div>
        </div>
        <div class="info-row">
            <div class="info-label">Revised CTC:</div>
            <div class="info-value"><span class="new-sal">₹ {{ number_format($incrementLetter->new_salary, 2) }}</span></div>
        </div>
        <div class="info-row">
            <div class="info-label">Increment:</div>
            <div class="info-value"><span class="badge">{{ $incrementLetter->increment_percentage }}%</span></div>
        </div>
        <div class="info-row"><div class="info-label">Effective From:</div><div class="info-value">{{ $incrementLetter->effective_date->format('d F Y') }}</div></div>
    </div>
    <p>We appreciate your dedication and expect continued excellence. Congratulations on this well-deserved recognition.</p>
    <div class="signature-row">
        <div class="sig-box"><div>{{ $incrementLetter->employee->full_name }}</div><div style="color:#666">Employee Acknowledgment</div></div>
        <div class="sig-box" style="text-align:right"><div>HR Department</div><div style="color:#666">Authorized Signatory</div></div>
    </div>
    <div class="footer">This is an official document generated by HRMS &bull; Confidential</div>
</div>
</body>
</html>
